"""
Stage 2: LLM Section Classification
------------------------------------

This module takes the candidate sections produced by Stage 1
(document structure analysis) and sends them to the LLM classifier.

Stage 2 does NOT:
    - analyze PDF structure
    - extract PDF text
    - perform OCR
    - extract equipment fields

Its only responsibility is:

    CandidateSection[]
          ↓
    classification payload
          ↓
    classify_sections()
          ↓
    useful/relevant sections
"""

from __future__ import annotations

import logging
from typing import Any

from backend.stage1_document_structure import CandidateSection
from src.llm.classifier import classify_sections

logger = logging.getLogger(__name__)


def build_classification_payload(
    candidates: list[CandidateSection],
) -> list[dict[str, Any]]:
    """
    Convert Stage 1 CandidateSection objects into the format expected
    by the LLM section classifier.

    The LLM needs information about the section itself, not the full
    PDF content at this stage.
    """

    return [
        {
            "section_id": section.section_id,
            "title": section.title,
            "section_number": section.section_number,
            "page_start": section.start_page,
            "page_end": section.end_page,
            "level": section.level,
        }
        for section in candidates
    ]


def classify_candidate_sections(
    candidates: list[CandidateSection],
):
    """
    Run Stage 2: ask the LLM which document sections are potentially
    useful for equipment information extraction.

    Parameters
    ----------
    candidates:
        Sections generated by Stage 1.

    Returns
    -------
    SectionClassificationResult
        Structured result returned by src.llm.classifier.classify_sections().
    """

    if not candidates:
        logger.warning("Stage 2 received no candidate sections.")
        return None

    document_sections = build_classification_payload(candidates)

    logger.info(
        "Stage 2: classifying %d candidate sections with LLM.",
        len(document_sections),
    )

    result = classify_sections(document_sections)

    logger.info("Stage 2 classification completed.")

    return result


def run_stage_2(
    candidates: list[CandidateSection],
) -> dict[str, Any]:
    """
    Run the complete Stage 2 pipeline and return a JSON-friendly result.

    This wrapper is useful for testing and for the global pipeline.
    """

    document_sections = build_classification_payload(candidates)

    if not document_sections:
        return {
            "stage": 2,
            "total_candidates": 0,
            "classification": None,
        }

    result = classify_sections(document_sections)

    # Pydantic model → dictionary if applicable
    if hasattr(result, "model_dump"):
        classification = result.model_dump()
    elif hasattr(result, "dict"):
        classification = result.dict()
    else:
        classification = result

    return {
        "stage": 2,
        "total_candidates": len(document_sections),
        "classification": classification,
    }